### ISSUE TITLE
2.93でToolパネルのItem→Vertex Weightsの数値ドラッグ操作ができなくなりました

### ISSUE THREAD

**Issue by Ogyly** [dskjal/Smooth-Normal#2]
blender2.93でSmooth Normalを使わせてもらっていましたが､最近Normals Smooth Tool アドオンを使用しているとVertex Weightsの数値情報をクリックドラッグしての操作ができなくなりました｡Normals Smooth Tool 以外のアドオンをすべて無効化して検証しましたが､数値ドラッグ操作はできないままだったのでこちらのアドオンが原因のようなのですが､どこかの設定と競合していることとかないですかね？Vertex Weights以外の数字操作はできます｡

**Comment by dskjal** [comment]
修正しました。

**Comment by Ogyly** [comment]
直りました｡ありがとうございます｡
